### ISSUE TITLE
Support for Cloudinary Storage

### ISSUE THREAD

**Issue by kidbombay** [stavro/arc#112]
Would be great to have a storage adaptor to post images to cloudinary!

**Comment by stavro** [comment]
I would be open to accepting this PR if it includes tests...

However, it is also straightforward to have `arc_cloudinary` as a separate dependency.  I am leaning towards about pulling out all of the S3-specific stuff into a separate repository as well, because dealing with optional dependencies is a bit of a pain in the ass with S3 being optional currently.
