### ISSUE TITLE
Attaching avatar to existing users.

### ISSUE THREAD

**Issue by jakeperry** [stavro/arc#216]
We are converting from rails to Phoenix 1.3 and we would like to just use the url output from rails to attach the existing rails avatar to the new Phoenix/Arc avatar.  I generate a `scope` of the user then also generated the `AppName.Avatar.store({url, scope})` and I get the` {:ok, "imagefilename.jpg"`} in return but nothing is being written to the `scope.avatar` field.  Although the files are being processed and uploaded to S3 as I have set in the uploader.  Is there a better way to do this process? 

Also is there a way to pass a url as a param to get it to attach?

**Comment by pedep** [comment]
Are you using `arc_ecto`?

When you say "[..] nothing is being written to `scope.avatar`" do you mean nothing is being persisted to the database? 
If that is the case, you probably want to use the `cast_attachments` macro provided by `arc_ecto`.
You can get it to accept paths (local and remote) by providing the allow_paths (see [this](https://github.com/stavro/arc_ecto/blob/master/lib/arc_ecto/schema.ex#L44))
`cast_attachments` also handles adding the file path to the changeset. 

This issue might be of help https://github.com/stavro/arc_ecto/issues/52

**Comment by jakeperry** [comment]
Hi @pedep I am using that macro.  There is a string that has to be written and persisted to the DB for the files to be loaded by Arc that is the part that is missing when I use a url.

**Comment by pedep** [comment]
How are you saving your attachments? Could you outline the process your have been using, and maybe show the contents of your definition and user module?

I think the problem you are having, is due to using the wrong function for storing the images.
If you want `arc_ecto` to handle persisting to db, you should not call the `.store` function manually.

The update process should look something like this
```elixir
user = Repo.get(User, 1)
changeset = User.changeset(user, %{avatar: "http://my.url/image.jpg"})

Repo.update(changeset)
```

and remember to add `cast_attachments` with `allow_paths: true`
```elixir
schema "users" do
  field :name,   :string
  field :avatar, AppName.Avatar.Type
end

# [...] 

def changeset(%User{} = user, attrs) do
  user
  |> cast(attrs, [:name, :email, :password])
  |> cast_attachments(attrs, [:avatar], allow_paths: true) # <-- Handles files (or paths) given on the :avatar key in the attrs map
  |> # [...]
end
```

Be aware that the `allow_paths: true` also allows local paths. See https://github.com/stavro/arc_ecto/issues/52 for a possible solution

https://github.com/stavro/arc_ecto for more on using arc with ecto
